{
 "title": "Gimbal Discovery",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Namespace", "query": "label_values(namespace)" },
   { "name": "Backend", "query": "label_values(backendname)" }
  ]
 },
 "panels": [
  {
   "title": "Number of Backends",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(gimbal_discoverer_info)" }
   ]
  },
  {
   "title": "Kubernetes Backends",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(gimbal_discoverer_info{backendtype=\"kubernetes\"})"
    }
   ]
  },
  {
   "title": "OpenStack Backends",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(gimbal_discoverer_info{backendtype=\"openstack\"})"
    }
   ]
  },
  {
   "title": "Replicated Services",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(gimbal_discoverer_replicated_services_total{namespace=~\"$Namespace\",backendname=~\"$Backend\"})",
     "legendFormat": "Replicated Services"
    }
   ]
  },
  {
   "title": "Replicated Endpoints",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(gimbal_discoverer_replicated_endpoints_total{namespace=~\"$Namespace\",backendname=~\"$Backend\"})",
     "legendFormat": "Replicated Services"
    }
   ]
  },
  {
   "title": "Replicated Services by Backend",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(gimbal_discoverer_replicated_services_total{namespace=~\"$Namespace\",backendname=~\"$Backend\"}) by (backendname)",
     "legendFormat": "Backend: {{ backendname }} "
    }
   ]
  },
  {
   "title": "Service replication success rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 4 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(gimbal_discoverer_replicated_services_total{namespace=~\"$Namespace\",backendname=~\"$Backend\"} / gimbal_discoverer_upstream_services_total{namespace=~\"$Namespace\",backendname=~\"$Backend\"}) by (backendname)",
     "legendFormat": "Backend: {{backendname}}"
    }
   ]
  },
  {
   "title": "Replicated Endpoints by Backend",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(gimbal_discoverer_replicated_endpoints_total{namespace=~\"$Namespace\",backendname=~\"$Backend\"}) by (backendname)",
     "legendFormat": "{{ backendname }}"
    }
   ]
  },
  {
   "title": "Endpoint replication success rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 4 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(gimbal_discoverer_replicated_endpoints_total{namespace=~\"$Namespace\",backendname=~\"$Backend\"}) by (backendname) / sum(gimbal_discoverer_upstream_endpoints_total{namespace=~\"$Namespace\",backendname=~\"$Backend\"}) by (backendname)",
     "legendFormat": "Backend: {{backendname}}"
    }
   ]
  },
  {
   "title": "Replicated Services by Namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(gimbal_discoverer_replicated_services_total{namespace=~\"$Namespace\",backendname=~\"$Backend\"}) by (namespace)",
     "legendFormat": "Namespace: {{ namespace }} "
    }
   ]
  },
  {
   "title": "Replicated Endpoints by Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(gimbal_discoverer_replicated_endpoints_total{namespace=~\"$Namespace\",backendname=~\"$Backend\"}) by (servicename)",
     "legendFormat": "{{ servicename }}"
    }
   ]
  },
  {
   "title": "Replicated Endpoints by Service & Backend",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(gimbal_discoverer_replicated_endpoints_total{namespace=~\"$Namespace\",backendname=~\"$Backend\"}) by (backendname, servicename)",
     "legendFormat": "{{ servicename }} / {{ backendname }}"
    }
   ]
  },
  {
   "title": "Endpoint replication success rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(gimbal_discoverer_replicated_endpoints_total{namespace=~\"$Namespace\",backendname=~\"$Backend\"}) by (servicename, backendname) / sum(gimbal_discoverer_upstream_endpoints_total{namespace=~\"$Namespace\",backendname=~\"$Backend\"}) by (servicename, backendname)",
     "legendFormat": "{{servicename}} / {{backendname}}"
    }
   ]
  },
  {
   "title": "Gimbal Replication Queue Size",
   "type": "graph",
   "description": "Size the event processing queue",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gimbal_queuesize{backendname=~\"$Backend\"} ",
     "legendFormat": "{{backendname}}"
    }
   ]
  },
  {
   "title": "Openstack API Latency: Load Balancers Endpoint",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(gimbal_discoverer_api_latency_milliseconds_bucket{path=~\".*loadbalancers.*\"}[5m])) by (le, kubernetes_pod_name))",
     "legendFormat": "{{kubernetes_pod_name}} 50%"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(gimbal_discoverer_api_latency_milliseconds_bucket{path=~\".*loadbalancers.*\"}[5m])) by (le, kubernetes_pod_name))",
     "legendFormat": "{{kubernetes_pod_name}} 99%"
    }
   ]
  },
  {
   "title": "Openstack API Latency: Pools Endpoint",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(gimbal_discoverer_api_latency_milliseconds_bucket{path=~\".*pools.*\"}[5m])) by (le, kubernetes_pod_name))",
     "legendFormat": "{{kubernetes_pod_name}} 50%"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(gimbal_discoverer_api_latency_milliseconds_bucket{path=~\".*pools.*\"}[5m])) by (le, kubernetes_pod_name))",
     "legendFormat": "{{kubernetes_pod_name}} 99%"
    }
   ]
  },
  {
   "title": "Openstack API Latency: Listeners",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(gimbal_discoverer_api_latency_milliseconds_bucket{path=~\".*listeners.*\"}[5m])) by (le, kubernetes_pod_name))",
     "legendFormat": "{{kubernetes_pod_name}} 50%"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(gimbal_discoverer_api_latency_milliseconds_bucket{path=~\".*listeners.*\"}[5m])) by (le, kubernetes_pod_name))",
     "legendFormat": "{{kubernetes_pod_name}} 99%"
    }
   ]
  },
  {
   "title": "Openstack Cycle Time",
   "type": "graph",
   "description": "Time to process all items within a cluster",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(gimbal_discoverer_cycle_duration_seconds_bucket{backendname=~\"$Backend\"}[5m])) by (le, kubernetes_pod_name))",
     "legendFormat": "{{kubernetes_pod_name}} 50%"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(gimbal_discoverer_cycle_duration_seconds_bucket{backendname=~\"$Backend\"}[5m])) by (le, kubernetes_pod_name))",
     "legendFormat": "{{kubernetes_pod_name}} 99%"
    }
   ]
  }
 ]
}
{
 "title": "Contour",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Namespace", "query": "label_values(namespace)" },
   { "name": "VHost", "query": "label_values(vhost)" }
  ]
 },
 "panels": [
  {
   "title": "Total IngressRoutes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(contour_ingressroute_total{namespace=~\"$Namespace\"}) by (namespace)",
     "legendFormat": "Namespace: {{ namespace }}"
    }
   ]
  },
  {
   "title": "Orphaned IngressRoutes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(contour_ingressroute_orphaned_total{namespace=~\"$Namespace\"}) by (namespace)",
     "legendFormat": "Namespace: {{ namespace }}"
    }
   ]
  },
  {
   "title": "Valid IngressRoutes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(contour_ingressroute_valid_total{namespace=~\"$Namespace\",vhost=~\"$VHost\"}) by (namespace,vhost)",
     "legendFormat": "Namespace: {{ namespace }} ({{ vhost }})"
    }
   ]
  },
  {
   "title": "Invalid IngressRoutes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(contour_ingressroute_invalid_total{namespace=~\"$Namespace\",vhost=~\"$VHost\"}) by (namespace,vhost)",
     "legendFormat": "Namespace: {{ namespace }} ({{ vhost }})"
    }
   ]
  },
  {
   "title": "Root IngressRoutes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(contour_ingressroute_root_total{namespace=~\"$Namespace\"}) by (namespace)",
     "legendFormat": "Namespace: {{ namespace }}"
    }
   ]
  },
  {
   "title": "Contour LDS Updates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_listener_manager_lds_update_failure",
     "legendFormat": "{{kubernetes_pod_name}} (failure)"
    },
    {
     "expr": "envoy_listener_manager_lds_update_success",
     "legendFormat": "{{kubernetes_pod_name}} (success)"
    },
    {
     "expr": "envoy_listener_manager_lds_update_rejected",
     "legendFormat": "{{kubernetes_pod_name}} (rejected)"
    }
   ]
  },
  {
   "title": "Contour CDS Updates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_cluster_manager_cds_update_success",
     "legendFormat": "{{kubernetes_pod_name}} (Success)"
    },
    {
     "expr": "envoy_cluster_manager_cds_update_failure",
     "legendFormat": "{{kubernetes_pod_name}} (Failure)"
    },
    {
     "expr": "envoy_cluster_manager_cds_update_rejected",
     "legendFormat": "{{kubernetes_pod_name}} (Rejected)"
    }
   ]
  },
  {
   "title": "Contour RDS Updates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_http_rds_ingress_http_update_success",
     "legendFormat": "{{kubernetes_pod_name}} (Success)"
    },
    {
     "expr": "envoy_http_rds_ingress_http_update_failure",
     "legendFormat": "{{kubernetes_pod_name}} (Failure)"
    },
    {
     "expr": "envoy_http_rds_ingress_http_update_rejected",
     "legendFormat": "{{kubernetes_pod_name}} (Rejected)"
    }
   ]
  }
 ]
}
{
 "title": "Envoy Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "query": "label_values(envoy_cluster_upstream_rq_time_bucket,namespace)"
   },
   {
    "name": "Service",
    "query": "label_values(envoy_cluster_upstream_rq_time_bucket,service)"
   }
  ]
 },
 "panels": [
  {
   "title": "Downstream RPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_total[1m])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Downstream CPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_cx_total[1m])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Downstream Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(envoy_http_downstream_rq_time_bucket[1m])) by (le, kubernetes_pod_name))",
     "legendFormat": "{{kubernetes_pod_name}} 90%"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(envoy_http_downstream_rq_time_bucket[1m])) by (le, kubernetes_pod_name))",
     "legendFormat": "{{kubernetes_pod_name}} 50% "
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(envoy_http_downstream_rq_time_bucket[1m])) by (le, kubernetes_pod_name))",
     "legendFormat": "{{kubernetes_pod_name}} 99%"
    }
   ]
  },
  {
   "title": "Downstream Total Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_http_downstream_cx_active) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Upstream RPS",
   "type": "graph",
   "description": "Displays the number of Requests per Second being performed against each Upstream.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_total{namespace=~\"$Namespace\",service=~\"$Service\"}[1m])) by (service,namespace)",
     "legendFormat": "{{namespace}}/{{service}}"
    }
   ]
  },
  {
   "title": "Upstream CPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_total{namespace=~\"$Namespace\",service=~\"$Service\"}[1m])) by (namespace, service)",
     "legendFormat": "{{namespace}}/{{service}}"
    }
   ]
  },
  {
   "title": "Upstream Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(envoy_cluster_upstream_rq_time_bucket{service=~\"$Service\",namespace=~\"$Namespace\"}[1m])) by (le, service, namespace))",
     "legendFormat": "{{namespace}}/{{service}} 99%"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(envoy_cluster_upstream_rq_time_bucket{service=~\"$Service\",namespace=~\"$Namespace\"}[1m])) by (le, service, namespace))",
     "legendFormat": "{{namespace}}/{{service}} 90%"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(envoy_cluster_upstream_rq_time_bucket{service=~\"$Service\",namespace=~\"$Namespace\"}[1m])) by (le, service, namespace))",
     "legendFormat": "{{namespace}}/{{service}} 50% "
    }
   ]
  },
  {
   "title": "Upstream Total Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_cx_active{namespace=~\"$Namespace\",service=~\"$Service\"}) by (namespace, service)",
     "legendFormat": "{{namespace}}/{{service}}"
    }
   ]
  },
  {
   "title": "Upstream 2xx Responses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{namespace=~\"$Namespace\",service=~\"$Service\",envoy_response_code_class=~\"2\"}[1m])) by (namespace,service)",
     "legendFormat": "{{namespace}}/{{service}}"
    }
   ]
  },
  {
   "title": "Upstream 3xx Responses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{namespace=~\"$Namespace\",service=~\"$Service\",envoy_response_code_class=\"3\"}[1m])) by (namespace,service)",
     "legendFormat": "{{namespace}}/{{service}}"
    }
   ]
  },
  {
   "title": "Upstream 4xx Responses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{namespace=~\"$Namespace\",service=~\"$Service\",envoy_response_code_class=\"4\"}[1m])) by (namespace,service)",
     "legendFormat": "{{namespace}}/{{service}}"
    }
   ]
  },
  {
   "title": "Upstream 5xx Responses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{namespace=~\"$Namespace\",service=~\"$Service\",envoy_response_code_class=\"5\"}[1m])) by (namespace,service)",
     "legendFormat": "{{namespace}}/{{service}}"
    }
   ]
  },
  {
   "title": "Endpoint Percentage Health",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(envoy_cluster_membership_healthy{namespace=~\"$Namespace\",service=~\"$Service\"}) by (namespace, service) / avg(envoy_cluster_membership_total{namespace=~\"$Namespace\",service=~\"$Service\"}) by (namespace, service)",
     "legendFormat": "{{namespace}}/{{service}}"
    }
   ]
  },
  {
   "title": "Total Endpoints",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(envoy_cluster_membership_total{namespace=~\"$Namespace\",service=~\"$Service\"}) by (namespace, service)",
     "legendFormat": "{{namespace}}/{{service}}"
    }
   ]
  },
  {
   "title": "Healthy Endpoints",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(envoy_cluster_membership_healthy{namespace=~\"$Namespace\",service=~\"$Service\"}) by (namespace, service)",
     "legendFormat": "{{namespace}}/{{service}}"
    }
   ]
  },
  {
   "title": "Unhealthy Endpoints",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(envoy_cluster_membership_total{namespace=~\"$Namespace\",service=~\"$Service\"}) by (namespace, service) - avg(envoy_cluster_membership_healthy{namespace=~\"$Namespace\",service=~\"$Service\"}) by (namespace, service)",
     "legendFormat": "{{namespace}}/{{service}}"
    }
   ]
  }
 ]
}